Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryList.Models
{
    public class Category
    {
        public string CategoryId { get; set; }
        public string Name { get; set; }
    }
}

Models/Grocery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace GroceryList.Models
{
       public class Grocery
       {
        
        public int Id { get; set; }
        public string Name { get; set; }
        [Required(ErrorMessage =" Please enter a number")]
        public double? UnitPrice { get; set; }

        public string CategoryId { get; set; }
        public Category Category { get; set; }

       
        
               
                
    }
}

Models/GroceryContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace GroceryList.Models
{
    public class GroceryContext : DbContext
    {
        public GroceryContext(DbContextOptions<GroceryContext> option) : base(option)
        { }

        public DbSet<Grocery> Grocerys { get; set; }
        public DbSet<Category> Categories { get; set; }




        //add inital data to the database
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>().HasData(
               new Category
               {
                   CategoryId = "F",
                   Name = "Frozen"
               },

               new Category
               {
                   CategoryId = "N",
                   Name = "Not Frozen"
               }

                 );                         

            modelBuilder.Entity<Grocery>().HasData(
                new Grocery
                {
                    Id = 1,
                    Name = "Steak",
                    UnitPrice = 19.5,
                    CategoryId = "F"
                    
                },
                new Grocery
                {
                    Id = 2,
                    Name = "Cereal",
                    UnitPrice = 2.99,
                    CategoryId = "N"
                    
                }
              

            );
        }

    }

}









Controllers/GroceryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GroceryList.Models;
using Microsoft.EntityFrameworkCore;

namespace GroceryList.Controllers
{
    public class GroceryController : Controller
    {
        private GroceryContext Context { get; set; }
        public GroceryController(GroceryContext ctx)
        {
            Context = ctx;

        }


        [HttpGet]

        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            ViewBag.Categories = Context.Categories.OrderBy(c => c.Name).ToList();
            return View("Edit", new Grocery());
        }
        [HttpGet]

        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.Categories = Context.Categories.OrderBy(c => c.Name).ToList();
            var Grocery = Context.Grocerys.Find(id);
            return View(Grocery);
        }
        [HttpPost]
        public IActionResult Edit(Grocery Grocery)
        {
            if (ModelState.IsValid)
            {
                if (Grocery.Id == 0)
                    Context.Grocerys.Add(Grocery);
                else
                    Context.Grocerys.Update(Grocery);
                Context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (Grocery.Id == 0) ? "ADD" : "Edit";
                ViewBag.Categories = Context.Categories.OrderBy(c => c.Name).ToList();
                return View(Grocery);
            }

        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            ViewBag.Action = "Delete";
            var Grocery = Context.Grocerys.Find(id);
            return View(Grocery);
        }

        [HttpPost]
        public IActionResult Delete(Grocery Grocery)
        {
            Context.Grocerys.Remove(Grocery);
            Context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }

}

                






            









            
        

    

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GroceryList.Models;

namespace GroceryList.Controllers
{
    public class HomeController : Controller
    {
        private GroceryContext Context { get; set; }
        public HomeController(GroceryContext ctx)
        {
            Context = ctx;
        }        
        public IActionResult Index()
        {
            var Grocerys = Context.Grocerys.Include(x=> x.Category).OrderBy(m => m.Name).ToList();
            return View(Grocerys);

        }




        //GET: Grocery/ShowSearchForm
        public IActionResult ShowSearchForm()
        {
            return View();

        }

        //POST: Grocery/ShowSearchResults
        public IActionResult ShowSearchResults(String SearchPhrase)
        {
            return View("Index", Context.Grocerys.Include(x => x.Category).Where(m => m.Name.Contains(SearchPhrase)).ToList());

        }







    }
}

Views/Grocery/Delete.cshtml
@model Grocery
@{ 
        ViewBag.Title = "Delete Grocery";
}
<h2> Confirm Deleteion</h2>
<h3> @Model.Name (@Model.UnitPrice)</h3>

<form asp-action="Delete" method="post">
<input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="Home" asp-action="Index"
    class="btn btn-primary">Cancel</a>

</form>

Views/Grocery/Edit.cshtml
@model Grocery
@{
    ViewData["Title"] = "View";
}

<h2>@ViewBag.Title</h2>
<form asp-action="Edit" method="post">
    <div asp-validation-summary="All" class="test-danger"></div>"
    <div class="form-group">
        <label asp-for="Id">Id</label>
        <input asp-for="Id" class="form-control" />

    </div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" />


    </div>
    <div class="form-group">
        <label asp-for="UnitPrice">UnitPrice</label>
        <input asp-for="UnitPrice" class="form-control" />


    </div>
    <div class="form-group">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" class="form-control" >
            <option value="">select a Category</option>
            @foreach (Category c in ViewBag.Categories)
            {
                <option value="@c.CategoryId">@c.Name</option>
            }
        </select>

    </div>



    <input type="hidden" asp-for="Id" />

    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

    

Views/Home/Index.cshtml
@model List<GroceryList.Models.Grocery>
@{
    ViewData["Title"] = "My Grocerys";
}

<h2>Grocery List</h2>

<a asp-controller="Grocery" asp-action="Add">Creat New</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>UnitPrice</th>
            <th>Category</th>
            <th>Action</th>
            <th>  </th>
        </tr>

    </thead>
    <tbody>
        @foreach (var Grocery in Model)
        {
        <tr>
            <td>@Grocery.Id</td>
            <td>@Grocery.Name</td>
            <td>@Grocery.UnitPrice</td>
            <td>@Grocery.Category.Name</td>


            <td>
                <a asp-controller="Grocery" asp-action="Edit" asp-route-id="@Grocery.Id">Edit</a>
                <a asp-controller="Grocery" asp-action="Delete" asp-route-id="@Grocery.Id">Delete</a>
            </td>
        </tr>

        }
    </tbody>
</table>




Views/Home/ShowSearchForm.cshtml
    <h4>Search for Grocery</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="ShowSearchResults">

                <div class="form-group">
                    <label for="SearchPhrase" class="control-label"></label>
                    <input name = "SearchPhrase" class="form-control" />

                </div>
                <div class="form-group">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GroceryList</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GroceryList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
      
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GroceryList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>